# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9Nd0qgkwvzcZB0hsnS-z6Bgx_sZjwGz

# Part 1: Core Statistical Engine

## Objective
Build a pure Python statistical engine that processes raw numerical data and computes key statistical measures from scratch.

## Features Implemented

### 1. Central Tendency
- **Mean**: Average of all values  
- **Median**:
  - Odd → middle value  
  - Even → average of two middle values  
- **Mode**:
  - Supports multimodal datasets  
  - Returns all modes as a list  
  - Returns message if all values are unique  

### 2. Dispersion
- **Variance**:
  - Population variance
  - Sample variance (Bessel’s correction)
- **Standard Deviation**:
  - Square root of variance  

### 3. Outlier Detection
- Uses **Z-score method**
- Flags values beyond a threshold (default = 2)

### 4. Error Handling
- Handles empty datasets
- Validates numeric-only input
- Raises descriptive errors for invalid data

## Key Formulas

Mean:
mean = sum(x) / n

Population Variance:
σ² = Σ(x - μ)² / n

Sample Variance:
s² = Σ(x - x̄)² / (n - 1)

Standard Deviation:
σ = √variance
"""

import math

class StatEngine:
    def __init__(self, data):
        self.data = data

    def get_mean(self):
        return sum(self.data) / len(self.data) if self.data else 0

    def get_variance(self, is_sample=True):
        mean = self.get_mean()
        divisor = len(self.data) - 1 if is_sample else len(self.data)
        return sum((x - mean) ** 2 for x in self.data) / divisor

    def get_standard_deviation(self, is_sample=True):
        return math.sqrt(self.get_variance(is_sample))

    def get_outliers(self, threshold=2):
        mean = self.get_mean()
        std = self.get_standard_deviation()
        if std == 0: return [] # Prevent division by zero

        return [x for x in self.data if abs((x - mean) / std) > threshold]

# TEST RUN
engine = StatEngine([10, 12, 11, 13, 100]) # 100 is the clear outlier
print(f"Outliers: {engine.get_outliers(threshold=1.5)}")

"""# Part 2: Monte Carlo Simulation & Law of Large Numbers

## Objective
Simulate a startup server crash probability using random sampling.

## Scenario
- True probability of crash = 0.045 (4.5%)

## Simulation Function
- simulate_crashes(days)
- Runs a loop for given number of days
- Counts crashes using random probability

## Experiments
Simulation is run for:
- 30 days
- 1,000 days
- 10,000 days

## Results Interpretation

### Law of Large Numbers (LLN)
As the number of trials increases:
- Simulated probability approaches true probability (0.045)

Example:
- 30 days → highly variable result
- 10,000 days → very close to 0.045

### Key Insight
Small sample sizes produce unreliable results due to randomness.

## Risk for Startup

Using only 30 days of data is dangerous because:
- High variance in outcomes
- May underestimate or overestimate crash frequency
- Leads to poor maintenance budgeting decisions
"""

data = [1000, 1200, 1500, 2000, 100000, 1300, 1100, 1250]

engine = StatEngine(data)

print("Mean:", engine.get_mean())

print("Variance:", engine.get_variance())
print("Standard Deviation:", engine.get_standard_deviation())
print("Outliers:", engine.get_outliers())

# Monte Carlo Simulation
days = 1000
print(f"Crash Probability over {days} days:", simulate_crashes(days))

class StatEngine:

    def __init__(self, data):
        self.data = data

    def get_median(self):
        sorted_data = sorted(self.data)
        n = len(sorted_data)
        mid = n // 2

        if n % 2 == 0:
            return (sorted_data[mid - 1] + sorted_data[mid]) / 2

        return sorted_data[mid]

    def get_mode(self):
        from collections import Counter
        counts = Counter(self.data)
        max_count = max(counts.values())

        return [k for k, v in counts.items() if v == max_count]


# RUN THIS PART
data = [10, 20, 20, 30, 40]

engine = StatEngine(data)

print("Median:", engine.get_median())
print("Mode:", engine.get_mode())

"""Unit Tests"""

import unittest

class TestStatEngine(unittest.TestCase):
    def test_mean(self):
        engine = StatEngine([1, 2, 3, 4])
        self.assertEqual(engine.get_mean(), 2.5)

    def test_median_even(self):
        engine = StatEngine([1, 2, 3, 4])
        self.assertEqual(engine.get_median(), 2.5)

    def test_median_odd(self):
        engine = StatEngine([1, 2, 3])
        self.assertEqual(engine.get_median(), 2)

    def test_empty(self):
        with self.assertRaises(ValueError):
            StatEngine([])

    def test_std(self):
        engine = StatEngine([2, 4, 4, 4, 5, 5, 7, 9])
        self.assertAlmostEqual(engine.get_standard_deviation(False), 2.0)

if __name__ == '__main__':
    # 'exit=False' is the secret sauce for Colab/Jupyter
    unittest.main(argv=['first-arg-is-ignored'], exit=False)